parameters:
    command_chain:
        FirstMasterCommandName:
            - ConsoleFirstChainCommandName
            - ConsoleSecondChainCommandName
            - ConsoleThirdChainCommandName
        SecondMasterCommandName:
            - ConsoleFifthChainCommand
            - ConsoleSecondChainCommand
            - ConsoleSecondChainCommand
        foo:hello:
            - bar:hi


