parameters:
    command_chain:
        FirstMasterCommandName:
            - ConsoleFirstChainCommandName
            - ConsoleSecondChainCommandName
            - ConsoleThirdChainCommandName
        SecondMasterCommandName:
            - ConsoleFifthChainCommand
            - ConsoleSecondChainCommand
            - ConsoleSecondChainCommand
        foo:hello:
            - bar:hi

    kernel.listener.command_dispatch:
        class: Zhora\CommandChainBundle\EventListener\ConsoleCommandListener
        tags:
            - { name: kernel.event_listener, event: console.command, priority: 1024 }

