version: '3.4'
#@see https://docs.docker.com/compose/compose-file/compose-file-v3/
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:
  php:
    build:
      context: ./docker/php/build
      dockerfile: Dockerfile
    container_name: example_app_php
    restart: unless-stopped
    volumes:
      - composer:/root/.composer/cache
      - ./app:/app
    logging: *default-logging

volumes:
  composer:
